import {test} from 'node:test';
import assert from 'node:assert/strict';
import {signal,sourceFrom,hash} from '../src/common.ts';
import {signalSchema,validatePublication} from '../src/schema.ts';
import {slug} from '../src/cities.ts';
const evidence={body:new Uint8Array([1,2]),sha256:hash(new Uint8Array([1,2])),retrievedAt:'2026-09-26T00:00:00Z',url:'https://example.org/data'};
const feature=signal({id:'test:abc',cityId:'koeln',kind:'place',category:'school',title:'Example',statement:'A school is listed.',status:'listed',startDate:null,endDate:null,nextStep:'Confirm operation.',unknowns:['Hours'],scale:'street',geometryPrecision:'exact',sources:[sourceFrom(evidence,'Source','Publisher','elements[0]')],extraction:{method:'structured'},reviewState:'candidate',asOf:'2026-09-26'}, {type:'Point',coordinates:[6.9,50.9]});
test('city IDs preserve expected transliteration and trim punctuation',()=>{assert.equal(slug('Düsseldorf'),'duesseldorf');assert.equal(slug('Köln / Münster'),'koeln-muenster');assert.equal(slug('Groß-Gerau'),'gross-gerau');assert.equal(slug('Évreux'),'vreux');});
test('validator rejects mismatched city and absent source snapshots masquerading as hashes',()=>{const catalogue={schemaVersion:'stadtstack-signals-v1',generatedAt:'2026-09-26',publisher:'Stadtstack',cities:[{id:'koeln',name:'Köln',state:'NRW',center:[6.9,50.9],bbox:[6,50,7,51],sources:[]}]};assert.equal(validatePublication(catalogue,{koeln:{type:'FeatureCollection',features:[feature]}}).collections.koeln.features.length,1);assert.throws(()=>validatePublication(catalogue,{koeln:{type:'FeatureCollection',features:[feature,feature]}}),/Duplicate/);assert.equal(signalSchema.safeParse({...feature,properties:{...feature.properties,sources:[{...feature.properties.sources[0],sha256:null,snapshot:true}]}}).success,false);assert.equal(signalSchema.safeParse({...feature,geometry:null}).success,false);assert.equal(signalSchema.safeParse({...feature,properties:{...feature.properties,extraction:{method:'llm'},reviewState:'reviewed'}}).success,false);});
