apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-backup-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ledger.helmLabels" . | nindent 4 }}
    app.kubernetes.io/name: ledger-of-life
    app.kubernetes.io/component: backup
data:
  backup.mjs: |
    {{- .Files.Get "files/backup.mjs" | nindent 4 }}
