import {cachedJson,signal,sourceFrom,sourceStatus} from './common.ts';
import type {City} from './cities.ts';
import type {Signal} from './schema.ts';
type Item={identifier:string;title?:string;subtitle?:string;description?:string[];point?:string;extent?:string;future?:boolean;isBlocked?:string;display_type?:string};
function coordinates(raw?:string):[number,number][]{if(!raw)return [];const a=raw.split(',').map(Number);if(a.length%2||a.some(x=>!Number.isFinite(x)))return [];const points:[number,number][]=[];for(let i=0;i<a.length;i+=2)points.push([a[i+1],a[i]]);return points;}
function active(item:Item){const dates=[...(item.description??[]).join(' ').matchAll(/(\d{2})\.(\d{2})\.(\d{2,4})/g)].map(m=>new Date(Number(m[3])<100?2000+Number(m[3]):Number(m[3]),Number(m[2])-1,Number(m[1])).getTime()).filter(Number.isFinite);return !dates.length||Math.max(...dates)>=Date.now()-86400000;}
function within(city:City,points:[number,number][]):boolean{if(!points.length)return false;const [w,s,e,n]=city.bbox,marginLat=25/111,marginLon=25/(111*Math.cos(city.center[1]*Math.PI/180));let west=Infinity,south=Infinity,east=-Infinity,north=-Infinity;for(const [lon,lat] of points){west=Math.min(west,lon);east=Math.max(east,lon);south=Math.min(south,lat);north=Math.max(north,lat);}return east>=w-marginLon&&west<=e+marginLon&&north>=s-marginLat&&south<=n+marginLat;}
export async function collectAutobahn(city:City){const features:Signal[]=[],sources:ReturnType<typeof sourceStatus>[]=[];for(const road of city.roads){for(const category of ['roadworks','closure'] as const){const url=`https://verkehr.autobahn.de/o/autobahn/${road}/services/${category}`;try{const e=await cachedJson<Record<string,Item[]>>(url,21600000);sources.push(sourceStatus(`autobahn-${road}-${category}`,'roadworks','Autobahn GmbH',url,'unknown',e.retrievedAt));for(const item of e.data[category]??[]){if(!active(item))continue;const points=coordinates(item.extent);if(!within(city,points.length?points:coordinates(item.point)))continue;const geometry:Signal['geometry']=points.length>=2&&points[0].join()!=points[1].join()?{type:'LineString',coordinates:points}:{type:'Point',coordinates:points[0]??coordinates(item.point)[0]};if(!geometry.coordinates)continue;
 const dates=[...(item.description??[]).join(' ').matchAll(/(\d{2})\.(\d{2})\.(\d{2,4})/g)].map(m=>`${Number(m[3])<100?2000+Number(m[3]):m[3]}-${m[2]}-${m[1]}`);
 const description=(item.description??[]).find(t=>t.includes('von ')||t.includes('zwischen '));
 const window=(item.description??[]).find(t=>/\d{2}\.\d{2}\.\d{2,4}\s+von/.test(t));
 features.push(signal({id:`autobahn:${item.identifier}`,cityId:city.id,kind:'roadworks',category:category==='closure'?'Sperrung':'Autobahn-Baustelle',title:item.title??`${road} ${category}`,statement:`${item.title??road}: ${category==='closure'?'eine Sperrung':'eine Baustelle'} ist im Autobahn-Verkehrsdienst verzeichnet${description?`. ${description.replace(/[\r\n]+/g,' ')}`:'.'} Die Lage kann auch eine Pendelstrecke außerhalb des Stadtgebiets betreffen.`,status:`${item.future?'angekündigt':'im Verkehrsdienst geführt'}${window?`; ${window}`:''}`,startDate:dates[0]??null,endDate:dates.at(-1)??null,nextStep:'Aktuelle Verkehrs- und Sperrinformationen beim Betreiber prüfen.',unknowns:['Genauer Verkehrsverlauf und tatsächliche Dauer vor Ort'],scale:'district',geometryPrecision:'approximate',sources:[sourceFrom(e,`Autobahn ${road} ${category}`,'Autobahn GmbH',`${category}[identifier=${item.identifier}]`,'unknown','unknown')],extraction:{method:'structured'},reviewState:'candidate',asOf:e.retrievedAt},geometry));}}catch(error){sources.push(sourceStatus(`autobahn-${road}-${category}`,'roadworks','Autobahn GmbH',url,'unknown',new Date().toISOString(),'failed',String(error)));}}}return {features,sources};}
