import {z} from 'zod';
const sha=z.string().regex(/^[a-f0-9]{64}$/);
export const faithfulnessGateSchema=z.object({score:z.number().min(.8).max(1),threshold:z.literal(.8),reason:z.string().min(1),evaluator:z.string().min(1),model:z.literal('codex:gpt-6-luna'),actual:z.literal(true),evaluatedAt:z.string().datetime(),statementHash:sha,contextHash:sha,evidenceHash:sha});
export const gatePolicy={metric:'DeepEval FaithfulnessMetric',metricVersion:'3.9.9',penalizeAmbiguousClaims:true,threshold:.8,model:'codex:gpt-6-luna'} as const;
export const verificationSchema=z.object({status:z.literal('auto-verified'),meaning:z.literal('Passed named automated gates; not human review or independent truth certification.'),evidenceBasis:z.literal('single-primary-source; no independent corroboration'),policy:z.object({metric:z.literal('DeepEval FaithfulnessMetric'),metricVersion:z.literal('3.9.9'),penalizeAmbiguousClaims:z.literal(true),threshold:z.literal(.8),model:z.literal('codex:gpt-6-luna')}),extractorVersion:z.string(),assertionHash:sha,sourceSha256:sha,deterministic:z.object({passed:z.literal(true),checks:z.array(z.string().min(1)).min(1)}),faithfulness:faithfulnessGateSchema});
export const coreFactSchema=z.object({id:z.string(),version:sha,topic:z.enum(['water','budget']),statement:z.string().min(1),assertion:z.object({date:z.string().optional(),year:z.number().int().optional(),value:z.number(),unit:z.enum(['m','EUR']),reference:z.string().optional()}),source:z.object({url:z.url(),sha256:sha,retrievedAt:z.string().datetime(),documentDate:z.string(),locator:z.string(),publisher:z.literal('Stadt Strausberg'),title:z.string()}),verification:verificationSchema});
export const coreBundleSchema=z.object({schemaVersion:z.literal('stadtstack-core-facts-v1'),cityId:z.literal('strausberg'),version:sha,generatedAt:z.string().datetime(),facts:z.array(coreFactSchema).length(3)});
export type CoreFact=z.infer<typeof coreFactSchema>;
export type CoreBundle=z.infer<typeof coreBundleSchema>;
