export interface GeoFeed {id:string;cityId:string;sourceType:'wfs'|'arcgis-rest';url:string;featureType?:string;version?:string;kind:'planning'|'roadworks';publisher:string;licence:string;limit:number;pageSize:number}
export const geoFeeds:GeoFeed[]=[
 {id:'koeln-bplan',cityId:'koeln',sourceType:'arcgis-rest',url:'https://geoportal.stadt-koeln.de/arcgis/rest/services/planen_und_bauen/b_plan_uebersicht/MapServer/1',kind:'planning',publisher:'Stadt Köln',licence:'Datenlizenz Deutschland – Zero 2.0 (dl-de/zero-2.0)',limit:1800,pageSize:200},
 {id:'koeln-baustelleneinrichtung',cityId:'koeln',sourceType:'wfs',url:'https://geoportal.stadt-koeln.de/wss/service/baustellen_wfs/guest',featureType:'ms:baustelleneinrichtung',version:'2.0.0',kind:'roadworks',publisher:'Stadt Köln',licence:'Datenlizenz Deutschland – Zero 2.0 (dl-de/zero-2.0)',limit:700,pageSize:180},
 {id:'koeln-strassenbauarbeiten',cityId:'koeln',sourceType:'wfs',url:'https://geoportal.stadt-koeln.de/wss/service/baustellen_wfs/guest',featureType:'ms:strassenbauarbeiten',version:'2.0.0',kind:'roadworks',publisher:'Stadt Köln',licence:'Datenlizenz Deutschland – Zero 2.0 (dl-de/zero-2.0)',limit:100,pageSize:100},
 {id:'koeln-ampelarbeiten',cityId:'koeln',sourceType:'wfs',url:'https://geoportal.stadt-koeln.de/wss/service/baustellen_wfs/guest',featureType:'ms:ampelarbeiten',version:'2.0.0',kind:'roadworks',publisher:'Stadt Köln',licence:'Datenlizenz Deutschland – Zero 2.0 (dl-de/zero-2.0)',limit:50,pageSize:50},
 {id:'muenster-bplan',cityId:'muenster',sourceType:'wfs',url:'https://geo.stadt-muenster.de/mapserv/bplan_serv',featureType:'ms:bplan2',version:'2.0.0',kind:'planning',publisher:'Stadt Münster',licence:'Datenlizenz Deutschland – Namensnennung 2.0 (dl-de/by-2-0), Attribution: Stadt Münster',limit:750,pageSize:200},
 {id:'muenster-baustellen',cityId:'muenster',sourceType:'wfs',url:'https://geo.stadt-muenster.de/mapserv/odbaustellen_serv',featureType:'baustellen',version:'1.1.0',kind:'roadworks',publisher:'Stadt Münster',licence:'Datenlizenz Deutschland – Namensnennung 2.0 (dl-de/by-2-0), Attribution: Stadt Münster',limit:100,pageSize:100},
];
