import {createServer} from 'node:http';
import {z} from 'zod';
import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {StreamableHTTPServerTransport} from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import type {Signal} from './schema.ts';
import {ensureRelease,type ReleasedData} from './mcp-release.ts';
import {cityIdSchema,querySchema,queryShape,queryFields,publicData} from './mcp-query.ts';
import {assertTopic,assignTopics,textMatches,topicMatches} from './topics.ts';
type Coord=[number,number];
const radians=Math.PI/180;
function distance(a:Coord,b:Coord){const lat=(a[1]+b[1])*radians/2,dx=(a[0]-b[0])*111195*Math.cos(lat),dy=(a[1]-b[1])*111195;return Math.hypot(dx,dy);}
function segmentDistance(p:Coord,a:Coord,b:Coord){const scale=111195*Math.cos((p[1]+a[1]+b[1])/3*radians);const x=(b[0]-a[0])*scale,y=(b[1]-a[1])*111195;if(!x&&!y)return distance(p,a);const t=Math.max(0,Math.min(1,((p[0]-a[0])*scale*x+(p[1]-a[1])*111195*y)/(x*x+y*y)));return distance(p,[a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);}
function inside(point:Coord,ring:Coord[]){let result=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])result=!result;}return result;}
function ringDistance(point:Coord,rings:Coord[][]){if(rings.length&&inside(point,rings[0])&&!rings.slice(1).some(r=>inside(point,r)))return 0;return Math.min(...rings.flatMap(r=>r.slice(1).map((b,i)=>segmentDistance(point,r[i],b))));}
export function geometryDistance(feature:Signal,point:Coord):number{const g=feature.geometry;if(!g)return Infinity;if(g.type==='Point')return distance(point,g.coordinates);if(g.type==='LineString')return Math.min(...g.coordinates.slice(1).map((b,i)=>segmentDistance(point,g.coordinates[i],b)));if(g.type==='Polygon')return ringDistance(point,g.coordinates);return Math.min(...g.coordinates.map(p=>ringDistance(point,p)));}
export function near(features:Signal[],point:Coord,radius:number,kinds?:string[]){return features.filter(f=>(!kinds||kinds.includes(f.properties.kind))&&geometryDistance(f,point)<=radius);}
export function searchText(features:Signal[],query?:string,topic?:string){
 assertTopic(topic);
 return features.filter(feature=>(!topic||assignTopics(`${feature.properties.title}\n${feature.properties.statement}`,[]).some(tag=>topicMatches(tag.id,topic)))&&textMatches(`${feature.properties.title}\n${feature.properties.statement}\n${feature.properties.category}\n${feature.properties.id}`,query));
}
export function along(features:Signal[],line:Coord[],buffer:number,kinds?:string[]){return features.filter(f=>(!kinds||kinds.includes(f.properties.kind))&&line.some((b,i)=>i>0&&geometryNearSegment(f,line[i-1],b,buffer)));}
function geometryNearSegment(feature:Signal,a:Coord,b:Coord,buffer:number){if(feature.geometry?.type==='Point')return segmentDistance(feature.geometry.coordinates,a,b)<=buffer;if(geometryDistance(feature,a)<=buffer||geometryDistance(feature,b)<=buffer)return true;const g=feature.geometry;if(!g)return false;const lines:Coord[][]=g.type==='LineString'?[g.coordinates]:g.type==='Polygon'?g.coordinates:g.coordinates.flat();for(const line of lines)for(let i=1;i<line.length;i++){const c=line[i-1],d=line[i];if(segmentDistance(c,a,b)<=buffer||segmentDistance(d,a,b)<=buffer)return true;const cross=(u:Coord,v:Coord,w:Coord)=>(v[0]-u[0])*(w[1]-u[1])-(v[1]-u[1])*(w[0]-u[0]);if(cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0)return true;}return false;}
export function server(options:{transformResult?:(data:unknown)=>{content:{type:'text';text:string}[];structuredContent?:Record<string,unknown>};release?:ReleasedData}={}) {
 const mcp=new McpServer({name:'stadtstack-data',version:'0.3.0'});
 const tool=options.transformResult??((data:unknown)=>{const safe=publicData(data);return {content:[{type:'text' as const,text:JSON.stringify(safe)}],structuredContent:typeof safe==='object'&&safe!==null&&!Array.isArray(safe)?safe as Record<string,unknown>:undefined};});
 const annotations={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false};
 const data=async()=>options.release??await ensureRelease();
 const id=z.string().min(1).max(256);
 const spatial={cursor:queryShape.cursor,limit:queryShape.limit,fields:queryShape.fields};
 const kinds=z.array(z.string().max(40)).max(20).optional();
 const comparisonFilters={query:queryShape.query,recordTypes:queryShape.recordTypes,sourceTypes:queryShape.sourceTypes,stage:queryShape.stage,dateFrom:queryShape.dateFrom,dateTo:queryShape.dateTo,excludePlaces:queryShape.excludePlaces,excludeOSM:queryShape.excludeOSM};
 mcp.registerTool('compare_topic',{description:'Compare normalized source-backed evidence for a shared topic across municipalities. Separate unknown/candidate/rejected/withdrawn evidence, dates, positive milestones and coverage. Not a municipal performance ranking.',inputSchema:z.object({...comparisonFilters,topic:z.string().min(1).max(80),cityIds:z.array(cityIdSchema).min(1).max(50)}).strict(),annotations},async({topic,cityIds,...filters})=>tool((await data()).index.compareTopic(topic,cityIds,filters)));
 mcp.registerTool('similar',{description:'Cross-city normalized case discovery using versioned deterministic text/topic Jaccard similarity, with scores, shared terms and source evidence. No model, S2Vec, causal or success claim. Candidate evidence stays explicit.',inputSchema:z.object({...comparisonFilters,id,topic:queryShape.topic,cityIds:z.array(cityIdSchema).min(1).max(50).optional(),limit:queryShape.limit}).strict(),annotations},async({id,limit,...filters})=>tool((await data()).index.similar(id,filters,limit)));
 mcp.registerTool('list_cities',{description:'Catalogue cities and separate regional/district evidence municipalities with registered source coverage. Evidence coverage is not whole-city catalogue coverage.',inputSchema:z.object({}).strict(),annotations},async()=>{const release=await data();return tool({...release.catalogue,regionalMunicipalities:[...release.index.municipalities.values()].filter(city=>city.coverage==='regional_evidence_only'),districtMunicipalities:[...release.index.municipalities.values()].filter(city=>city.districtId),knowledgeCoverage:release.index.knowledge?.coverage??null});});
 mcp.registerTool('list_topics',{description:'Shared hierarchical vocabulary preserving regional topic IDs, source/rule/model provenance, and eligible/withheld per-city counts. Parent counts include descendant topics without double counting records.',inputSchema:z.object({cityIds:z.array(cityIdSchema).min(1).max(50).optional()}).strict(),annotations},async({cityIds})=>tool((await data()).index.listTopics(cityIds)));
 mcp.registerTool('get_core_bundle',{description:'Read the exact shared core fact bundle and core release manifest. Auto-verified is not human review or independent truth certification.',inputSchema:z.object({}).strict(),annotations},async()=>{const release=await data();return tool({bundle:release.bundle,manifest:release.manifest});});
 mcp.registerTool('get_release_status',{description:'Whole-data release identity and quality summary, plus preserved separate core bundle/corpus manifest. Publication dates are not original event dates.',inputSchema:z.object({}).strict(),annotations},async()=>{const release=await data();return tool({dataManifest:release.dataManifest,manifest:release.manifest,coreGeneratedAt:release.bundle.generatedAt,catalogueGeneratedAt:release.catalogue.generatedAt,regionalGeneratedAt:release.regional.generatedAt});});
 mcp.registerTool('search_signals',{description:'Search released city or regional municipality records by shared topic/text. Source IDs only; fetch attribution with get_source. Release/filter-bound cursor paging; no offset.',inputSchema:z.object({...queryShape,cityId:cityIdSchema}).strict(),annotations},async({cityId,...query})=>tool((await data()).index.page({...query,cityIds:[cityId]},'search_signals')));
 mcp.registerTool('search_topics',{description:'Search released catalogue, regional and normalized knowledge records using one hierarchical topic vocabulary and German text rules. Source dates and verification gates remain explicit. Release/filter-bound cursor paging.',inputSchema:querySchema,annotations},async(query)=>tool((await data()).index.page(query,'search_topics')));
 mcp.registerTool('get_council_items',{description:'Released council papers/meetings, including regional agenda evidence. Source/event dates are separate from observation/publication time. Same filters/projection/cursor as search_topics.',inputSchema:z.object({...queryShape,cityId:cityIdSchema.optional()}).strict(),annotations},async({cityId,...query})=>{const release=await data();return tool(release.index.page({...query,cityIds:cityId?[cityId]:undefined},'get_council_items',release.index.records.filter(record=>record.recordType==='council_paper'||record.recordType==='council_meeting')));});
 mcp.registerTool('get_regional_topics',{description:'Regional and normalized district evidence discovery with shared DTO. Unknown source dates/stages and candidate gates remain comparisonEligible:false. Does not imply full municipal coverage.',inputSchema:z.object({...queryShape,municipalityId:cityIdSchema.optional()}).strict(),annotations},async({municipalityId,...query})=>{const release=await data();return tool({region:release.regional.region,knowledgeCoverage:release.index.knowledge?.coverage??null,...release.index.page({...query,cityIds:municipalityId?[municipalityId]:undefined},'get_regional_topics',release.index.records.filter(record=>record.origin==='regional'||record.origin==='knowledge'),null,true)});});
 mcp.registerTool('search_signals_near',{description:'Geometry near a point. Null-geometry records cannot match. Same projected record DTO and release/filter-bound cursor; no offset.',inputSchema:z.object({cityId:cityIdSchema,lon:z.number().min(-180).max(180),lat:z.number().min(-90).max(90),radius_m:z.number().positive().max(100000),kinds,...spatial}).strict(),annotations},async({cityId,lon,lat,radius_m,kinds,...page})=>{
   const release=await data();release.index.assertCities([cityId]);
   const matches=new Set(near(release.features.filter(feature=>feature.properties.cityId===cityId),[lon,lat],radius_m,kinds).map(feature=>feature.properties.id));
   return tool(release.index.page({...page,cityIds:[cityId]},'search_signals_near',release.index.records.filter(record=>record.cityId===cityId&&record.origin==='city'&&matches.has(record.id)),{lon,lat,radius_m,kinds}));
 });
 mcp.registerTool('search_signals_along',{description:'Geometry intersecting a buffered line, at most 32 vertices. Same projected record DTO and release/filter-bound cursor; no offset.',inputSchema:z.object({cityId:cityIdSchema,line:z.array(z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90)])).min(2).max(32),buffer_m:z.number().positive().max(50000),kinds,...spatial}).strict(),annotations},async({cityId,line,buffer_m,kinds,...page})=>{
   const release=await data();release.index.assertCities([cityId]);
   const matches=new Set(along(release.features.filter(feature=>feature.properties.cityId===cityId),line,buffer_m,kinds).map(feature=>feature.properties.id));
   return tool(release.index.page({...page,cityIds:[cityId]},'search_signals_along',release.index.records.filter(record=>record.cityId===cityId&&record.origin==='city'&&matches.has(record.id)),{line,buffer_m,kinds}));
 });
 mcp.registerTool('get_signal',{description:'Fetch a released record by stable fact/record ID, with all query DTO fields and source IDs (no duplicated attribution).',inputSchema:z.object({id}).strict(),annotations},async({id})=>{const release=await data();const record=release.index.records.find(record=>record.id===id);if(!record)throw Error('Record not found');return tool(Object.fromEntries(queryFields.map(field=>[field,record[field]])));});
 mcp.registerTool('get_sources',{description:'Fetch original attribution by fact/record ID, NOT by source ID. get_source accepts a source ID. Preserves fact verification evidence.',inputSchema:z.object({id}).strict(),annotations},async({id})=>{const release=await data();const record=release.index.records.find(record=>record.id===id);if(!record)throw Error('Record not found');return tool({id,sourceIds:record.sourceIds,sources:record.sourceIds.map(sourceId=>release.index.sources.get(sourceId)),eventDate:record.eventDate,asOf:record.asOf,status:record.verification?.status==='auto-verified'?'auto-verified':'candidate',reviewState:record.reviewState,verification:record.verification,assertion:record.assertion,geometryPrecision:record.geometryPrecision});});
 mcp.registerTool('get_source',{description:'Fetch one public attribution object by source ID returned in sourceIds. This is distinct from get_sources fact-ID lookup.',inputSchema:z.object({sourceId:id}).strict(),annotations},async({sourceId})=>{const source=(await data()).index.sources.get(sourceId);if(!source)throw Error('Source not found');return tool(source);});
 mcp.registerTool('get_changes',{description:'Catalogue stable IDs added, changed and removed in this immutable release. Regional evidence has no whole-city changes catalogue.',inputSchema:z.object({cityId:cityIdSchema}).strict(),annotations},async({cityId})=>{const release=await data();if(!Object.hasOwn(release.changes,cityId))throw Error('Unknown catalogue city');return tool(release.changes[cityId]);});
 return mcp;
}
if(process.argv[1]&&new URL(import.meta.url).pathname===process.argv[1]){if(process.argv.includes('--http')){const port=Number(process.env.STADTSTACK_MCP_PORT??'4318');const http=createServer(async(req,res)=>{if(!req.url?.startsWith('/mcp')){res.writeHead(req.url==='/health'?200:404,{'content-type':'application/json'});res.end(JSON.stringify({ok:req.url==='/health'}));return;}const instance=server(),transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined});try{await instance.connect(transport);await transport.handleRequest(req,res);}catch(error){console.error(error);if(!res.headersSent){res.writeHead(500);res.end();}}});http.listen(port,'127.0.0.1',()=>console.error(`Stadtstack MCP http://127.0.0.1:${port}/mcp`));}else{await server().connect(new StdioServerTransport());}}
